# Generated by Django 3.2 on 2021-04-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Albums', models.URLField()),
                ('Tracks', models.URLField()),
                ('Self', models.URLField()),
            ],
        ),
    ]
