# Generated by Django 3.2 on 2021-04-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0002_auto_20210427_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Self',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Tracks',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Albums',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Self',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='Tracks',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Self',
            new_name='self',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Times_Played',
            new_name='times_Played',
        ),
    ]
