# Generated by Django 3.2 on 2021-04-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0003_auto_20210428_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artista',
            name='id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
