# Generated by Django 3.2 on 2021-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0006_auto_20210429_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='artist_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
