# Generated by Django 3.2 on 2021-04-30 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0007_auto_20210429_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ar_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicAPI.artista'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='al_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicAPI.album'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='ar_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicAPI.artista'),
        ),
    ]
