# Generated by Django 3.2 on 2021-04-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0008_auto_20210430_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='times_Played',
            new_name='times_played',
        ),
    ]
