# Generated by Django 3.2 on 2021-04-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Genre', models.CharField(default=None, max_length=100)),
                ('Artist', models.URLField(default=None)),
                ('Tracks', models.URLField(default=None)),
                ('Self', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Duration', models.FloatField(default=None)),
                ('Times_Played', models.IntegerField(default=None)),
                ('Artist', models.URLField(default=None)),
                ('Album', models.URLField(default=None)),
                ('Self', models.URLField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='artista',
            name='Albums',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='artista',
            name='Self',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='artista',
            name='Tracks',
            field=models.URLField(default=None),
        ),
    ]
